#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 15 19:25:41 2021

@author: abram
"""

from numpy.random import choice
import numpy as np
from sklearn.metrics import euclidean_distances

def exploratory_kmeans_plusplus(n_clusters, data, data_weights, fixed_centroids):
    """
    

    Parameters
    ----------
    n_clusters : TYPE
        DESCRIPTION.
    data : TYPE
        DESCRIPTION.
    fixed_centroids : TYPE
        DESCRIPTION.

    Returns
    -------
    None.

    """
    n_fixed_centroids , _ = fixed_centroids.shape
    n_points , _ = data.shape
    
    n_new_centroids = n_clusters - n_fixed_centroids
    
    centers = fixed_centroids
    
    if n_new_centroids < 0:
        raise "Yeah this is a problem because the algorithm won't do anything"
        
    pos = euclidean_distances(X = data, Y = centers).min(axis = 1)
    weighted_pos = data_weights * pos
    cumulative_pos = weighted_pos.sum()
    
    probabilities = np.full(n_points, 0, dtype = float)
    for i in range(0,n_points):
            probabilities[i] = weighted_pos[i]/cumulative_pos
    
    
    for j in range(n_fixed_centroids, n_clusters):
        sample_indices = choice(range(0,n_points), 2 + round(np.ln(n_clusters)), p = probabilities)
        samples = data[sample_indices]
        
        total_pot = euclidean_distances(samples, fixed_centroids).sum(axis = 1)
        top_candidate = np.argmax(total_pot) #slapdash but better than sklearn's!
        
        centers[j] = samples[top_candidate]
        
        pos = euclidean_distances(X = data, Y = centers).min(axis = 1)
        weighted_pos = data_weights * pos
        cumulative_pos = weighted_pos.sum()
    
        probabilities = np.full(n_points, 0, dtype = float)
        for i in range(0,n_points):
            probabilities[i] = weighted_pos[i]/cumulative_pos
    
    movable_centroids = centers[n_fixed_centroids-1:n_clusters-1]
    
    return centers, fixed_centroids, movable_centroids

def exploratory_kmeans(data, data_weighting, fixed_centroids, movable_centroids):
    """
    
    
    

    Parameters
    ----------
    data : TYPE
        DESCRIPTION.
    data_weighting : TYPE
        DESCRIPTION.
    fixed_centroids : TYPE
        DESCRIPTION.
    movable_centroids : TYPE
        DESCRIPTION.

    Returns
    -------
    None.

    """
    

        
        